-- Drop old tables with PascalCase names
DROP TABLE IF EXISTS MerchantFollow;
DROP TABLE IF EXISTS ReferralCode;
DROP TABLE IF EXISTS Referral;
DROP TABLE IF EXISTS ApiKey;
DROP TABLE IF EXISTS ApiKeyUsage;
DROP TABLE IF EXISTS RefundRequest;
DROP TABLE IF EXISTS DashboardEvent;
DROP TABLE IF EXISTS LedgerEvent;
DROP TABLE IF EXISTS Bookmark;
DROP TABLE IF EXISTS Purchase;
DROP TABLE IF EXISTS AccessToken;
DROP TABLE IF EXISTS Payment;
DROP TABLE IF EXISTS PaymentIntent;
DROP TABLE IF EXISTS Content;
DROP TABLE IF EXISTS Merchant;

